baseURL = 'https://epicboy-manas.github.io/myblog/'
languageCode = 'en-us'
title = 'My New Hugo Site'

DefaultContentLanguage = 'en'
SectionPagesMenu = 'main'
[pagination]
  pagerSize = 10
enableRobotsTXT = true

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[params]
description = "The last theme you'll ever need. Maybe."
background_color_class = "bg-black"
recent_posts_number = 3
text_color = ""
author = ""
favicon = ""
site_logo = ""

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[languages.en]
title = "Ananke"
weight = 1
contentDir = "content"

[languages.fr]
title = "Ananke Fr"
weight = 2
contentDir = "content"
